name: Merge camperbot PR's

on:
  pull_request:
    types: [opened, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_PAT }}

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge camperbot PR
        if: github.actor == 'moT01'
        uses: actions/github-script@v6
        with:
          script: |
            const pr_number = context.payload.pull_request.number;
            const { owner, repo } = context.repo;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const pr = await octokit.rest.pulls.get({
              owner,
              repo,
              pull_number: pr_number
            });

            if (pr.data.user.login === 'moT01') {
              await octokit.rest.pulls.merge({
                owner,
                repo,
                pull_number: pr_number
              });
            } else {
              console.log('PR author is not moT01');
