name: Merge camperbot PR's

on:
  pull_request:
    types: [opened, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_PAT }}

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth login --with-token <<< "${GITHUB_TOKEN}"

      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_user=$(gh pr view ${{ github.event.pull_request.number }} --json author --jq '.author.login')
          if [ "$pr_user" = "moT01" ]; then
            gh pr merge ${{ github.event.pull_request.number }} --merge
          else
            echo "PR author is not camperbot, skipping merge."
          fi
